apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csv-api
  template:
    metadata:
      labels:
        app: csv-api
    spec:
      containers:
      - name: csv-api
        image: yourusername/csv-api
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data.csv
          subPath: data.csv
      volumes:
      - name: data-volume
        configMap:
          name: csv-config
---
apiVersion: v1
kind: Service
metadata:
  name: csv-api-service
spec:
  selector:
    app: csv-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
